/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mediator;

public class App {
    public static void main(String[] args) {
        Telstra telstra = new Telstra();
        TMobile tMobile = new TMobile();
        Phone phone1 = new SamsungPhone(telstra, "111");
        Phone phone2 = new ApplePhone(telstra, "222");

        Phone phone3 = new SamsungPhone(tMobile, "333");
        Phone phone4 = new ApplePhone(tMobile, "444");

        phone1.sendSMS("hello", "222");
        phone2.sendSMS("hi!", "111");

        phone4.sendSMS("hello", "333");
        phone3.sendSMS("hi!", "444");
    }
}
