/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Rule;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnit;
import org.mockito.junit.MockitoRule;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class MyClassTest {

    @Test
    public void doSomethingTest() {
        MyDependency dependencyMock = mock(MyDependency.class);
        MyClass myClass = new MyClass(dependencyMock);


        when(dependencyMock.getString(false)).thenReturn(null);
        when(dependencyMock.getString(true)).thenReturn("not null");

        String ret = myClass.doSomething(false);
        assertEquals("one thing", ret);
        verify(dependencyMock, times(1)).getString(anyBoolean());
        verify(dependencyMock, times(1)).getInt();
        verify(dependencyMock, times(1)).doThis();


        ret = myClass.doSomething(true);
        assertEquals("another thing", ret);
        verify(dependencyMock, times(2)).getString(anyBoolean());
        verify(dependencyMock, times(2)).getInt();
        verify(dependencyMock, times(2)).doThis();


    }
}
