/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnit;
import org.mockito.junit.MockitoRule;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class MyClassTest {

    @Mock
    MyDependency mockDependency;

    MyClass myClass;

    @Rule
    public MockitoRule mockitoRule = MockitoJUnit.rule();

    @Before
    public void setup() {
        String example = "Setup String";
        when(mockDependency.getString(false)).thenReturn(null);
        when(mockDependency.getString(true)).thenReturn("not null");
    }


    @Test
    public void doSomethingTest() {
        myClass = new MyClass(mockDependency);

        String ret = myClass.doSomething(false);
        assertEquals("one thing", ret);
        verify(mockDependency, times(1)).getString(anyBoolean());
        verify(mockDependency, times(1)).getInt();
        verify(mockDependency, times(1)).doThis();


        ret = myClass.doSomething(true);
        assertEquals("another thing", ret);
        verify(mockDependency, times(2)).getString(anyBoolean());
        verify(mockDependency, times(2)).getInt();
        verify(mockDependency, times(2)).doThis();


    }
}
