/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public interface MyDependency {
    public String getString(boolean bool);
    public int getInt();
    public void doThis();
}

