/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mypackage;

public class MyClass {
        private MyDependency dependency;

        public MyClass(MyDependency dependency) {
            this.dependency = dependency;
        }

        public String doSomething() {
            // you don't know what is in here
//            dependency.getSomeResult("STRING1", 1);
//            dependency.getSomeResult("STRING2", 2);
            return "";
        }
    }


