/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ExampleTesting;

import org.junit.Test;
import static org.junit.Assert.*;

public class MyClassTest {
    @Test
    public void getValueTest() {
        assertEquals("getValue returned the wrong value", 4, MyClass.getValue());
    }
}
