/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookWithBridge;

public class Book {
    private BookLength length;
    private BookGenre genre;
    private BookLanguage language;
    private BookType type;

    public Book(BookLength length, BookGenre genre, BookLanguage language, BookType type) {
        this.length = length;
        this.genre = genre;
        this.language = language;
        this.type = type;
    }

    public void read() {
        System.out.println("Reading " + type.getBookType());
        System.out.println("Reading in " + language.getBookLanguage());
        System.out.println("Reading " + genre.getBookGenre());
        System.out.println("The book is a " + length.getBookLength());
    }
}
