/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tut2;

import org.junit.Test;
import static org.junit.Assert.*;

public class CheckColissionTestSuite {


    //use lecture slides to perform the same tests as I just outlined in CollisionTestSuite
    //but use parameters to make it easier

}
